In [10]:
import numpy as np


In [11]:
A=np.array([1,2,3,4])
B=np.array([0,2,3,1])
np.dot(A,B)


17

In [12]:
#3d Array
C=np.array([
    [[1,2,3],[1,4,5]],
    [[3,4,5],[2,8,9]]
    ])
C

array([[[1, 2, 3],
        [1, 4, 5]],

       [[3, 4, 5],
        [2, 8, 9]]])

In [13]:
#prodotto matriciale
A=np.array([
        [1,2,3],
        [4,5,6],
        [7,8,10]])
B=[1,2,3]

#metodo 1 (build in funciton)
C=np.matmul(A,B)
C


array([14, 32, 53])

In [14]:
#metodo 2 (utilizzo di @)
D=A @ B
D

array([14, 32, 53])