In [1]:
import numpy as np


In [2]:
A=np.array([1,2,3,4])
B=np.array([0,2,3,1])
np.dot(A,B)


17

In [3]:
#3d Array
C=np.array([
    [[1,2,3],[1,4,5]],
    [[3,4,5],[2,8,9]]
    ])
C

array([[[1, 2, 3],
        [1, 4, 5]],

       [[3, 4, 5],
        [2, 8, 9]]])

In [4]:
#prodotto matriciale
A=np.array([
        [1,2,3],
        [4,5,6],
        [7,8,10]])
B=[1,2,3]

#metodo 1 (build in funciton)
C=np.matmul(A,B)
C


array([14, 32, 53])

In [5]:
#metodo 2 (utilizzo di @)
D=A @ B
D

array([14, 32, 53])

In [6]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x25894aef910>)

In [7]:
data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)
data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [8]:
yields=data @ [1,2,3]
yields

array([474., 379., 380., ..., 397., 485., 398.])

In [9]:
yields.shape

(10000,)